data_path: data/concatenated_anekdot_dataset.csv
train_batch_size: 32
val_batch_size: 64
train_size: 0.8
epochs: 5
lr1: 2e-4
lr2: 2e-5
weight_decay: 0.05
fp16: True
max_len: 150
model_dir: outputs/models
optim: AdamW
device: cuda
patience: 5
inference_size: 4
seed: 42
latent_dim: 512
tsne: 1024
grad_accumulation_steps: 4
warmup_steps: 1 # in epochs
beta_max: 0.01
beta_anneal_steps: 1 # in epochs
scheduler_type: linear
encoder_name: ai-forever/ruBert-large
decoder_name: ai-forever/rugpt3small_based_on_gpt2
lora: True
lora_modules:
 - c_attn
 - c_proj
 - c_fc

# resume: outputs/models/TransformerAnekdotGenerator_last.pt

# @TODO: REFACTOR ALL!!!
# LoRA maybe (peft) !!! 
