data_path: /mnt/e/datasets/funny_text_generator/parquet/concatenated_anekdot_dataset_v2_1_2M_w_annot.parquet
train_batch_size: 16
val_batch_size: 32
train_size: 0.99
epochs: 5
lr1: 2e-4
lr2: 2e-5
weight_decay: 0.05
fp16: True
max_len: 150
model_dir: outputs/models
optim: AdamW
device: cuda
patience: 5
inference_size: 4
seed: 42
latent_dim: 512
tsne: 1024
grad_accumulation_steps: 8
warmup_steps: 1 # in epochs
beta_max: 1
beta_anneal_steps: 1 # in epochs
lambda_: 0.2
scheduler_type: linear
word_dropout: 0.8
workers: 5
profile: True
n_tokens: 1
encoder_name: ai-forever/ruBert-base
decoder_name: ai-forever/rugpt3large_based_on_gpt2
name: n_tokens_1_wd_0.8_lora_c_attn_c_proj_c_fc_minimal_mapping_cls_heads
lora: True
lora_modules:
  - c_attn
  - c_proj
  - c_fc
num_themes: 226
num_actors: 200
num_mechanisms: 56

# resume: outputs/models/TransformerAnekdotGenerator_last.pt

# @TODO: REFACTOR ALL!!!

# Packing (батч превращаем в сполшной текст с <EOS> между ними)
# mean в KL loss и подобрать beta для масштаба
# meta-llama/Llama-3.2-1B FA-2
# qwen 2.5 1.5B FA-2
# deepvk/RuModernBERT-base
# loss на attention между Q и K для токенов z

# несколько шагов энкодер + маппинг перед обучением декодера
# log_var_layer.weight ~= 1e-4, bias=0
# заморозка энкодера кроме последних 2 слоев
