data_path: data/concatenated_anekdot_dataset.csv
train_batch_size: 32
val_batch_size: 64
train_size: 0.8
epochs: 100
lr: 2e-4
weight_decay: 0.05
fp16: True
d_model: 512
nhead: 8
dim_feedforward: 2048
reduction: sum
num_layers: 5
vocab_size: 50000
max_len: 150
model_dir: outputs/models
optim: AdamW
device: cuda
patience: 20
inference_size: 4
train_tokenizer: False
tokenizer_path: outputs/tokenizers/tokenizer.json
seed: 42
dropout: 0.1
word_dropout: 0.2 # for decoder
mask_p: 0.0
latent_dim: 128
tsne: 1024
grad_accumulation_steps: 4
warmup_steps: 0.3 # in epochs
# beta_max: 0.5
# beta_anneal_steps: 100 # in epochs
# beta_warmup_steps: 100 # in epochs
beta_max_base: 0.5
beta_anneal_cycle_length: 10
beta_anneal_ramp_ratio: 0.5
beta_anneal_warmup_cycles: 2
gaussian_nll: False
  
# resume: outputs/models/TransformerAnekdotGenerator_last.pt

# @TODO: REFACTOR ALL!!!
# Maybe cyclical beta scheduler
# How to implement with beta warmup???